# basic 
title: LACNet Networks
description: LACChain Networks
baseurl:
url:

# build settings
markdown: kramdown

github:
  # key: value
  # another_url: value

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-github-metadata


