# Basic 
title: LACNet Networks
description: LACChain Networks
baseurl:
url: 

# Build settings
# theme: minima
# theme: bulma-clean-theme
# markdown: kram down
# theme: minima

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

