# Basic 
title: LACNet Networks
description: LACChain Networks
baseurl:
url:
"logo": true


# Build settings
# theme: minima
# theme: bulma-clean-theme
# markdown: kram down
# theme: minima

github:
  # zip_url: http://example.com/download.zip
  # another_url: another value

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


